<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>NBA 2K Court Creator Portable</AssemblyName>
    <ApplicationIcon>../../src/NBA2KCourtCreator/Assets/app-icon.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(BundleInfoPath)" />
  </ItemGroup>
</Project>
