<Project>
  <PropertyGroup>
    <CanvasToolkitVersion Condition="'$(CanvasToolkitVersion)' == ''">0.9.15</CanvasToolkitVersion>
    <CanvasToolkitFeed Condition="'$(CanvasToolkitFeed)' == ''">$(MSBuildThisFileDirectory)..\..\source\artifacts\packages\$(CanvasToolkitVersion)</CanvasToolkitFeed>
    <RestoreAdditionalProjectSources>$(RestoreAdditionalProjectSources);$(CanvasToolkitFeed)</RestoreAdditionalProjectSources>
  </PropertyGroup>
</Project>
